# Generated by Django 5.2.4 on 2026-01-01 18:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('source_name', models.CharField(max_length=100)),
                ('source_lat', models.FloatField()),
                ('source_lng', models.FloatField()),
                ('destination_name', models.CharField(max_length=100)),
                ('destination_lat', models.FloatField()),
                ('destination_lng', models.FloatField()),
                ('distance_km', models.FloatField(default=0)),
                ('estimated_duration', models.IntegerField(help_text='Minutes')),
                ('polyline', models.TextField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='RouteStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.FloatField()),
                ('longitude', models.FloatField()),
                ('order', models.PositiveIntegerField()),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='routes.route')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
    ]
