# Generated by Django 5.2.9 on 2025-12-18 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('source', models.CharField(max_length=100)),
                ('destination', models.CharField(max_length=100)),
                ('distance_km', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estimated_duration_minutes', models.IntegerField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['source', 'destination'],
            },
        ),
        migrations.CreateModel(
            name='Bus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bus_number', models.CharField(max_length=20, unique=True)),
                ('bus_name', models.CharField(max_length=100)),
                ('bus_type', models.CharField(choices=[('ac', 'AC'), ('non_ac', 'Non-AC'), ('sleeper', 'Sleeper'), ('semi_sleeper', 'Semi-Sleeper')], default='ac', max_length=20)),
                ('total_seats', models.IntegerField(default=40)),
                ('departure_time', models.TimeField()),
                ('arrival_time', models.TimeField()),
                ('fare', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amenities', models.TextField(blank=True, help_text='Comma-separated amenities')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('driver', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bus', to='users.driver')),
                ('route', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='buses', to='buses.route')),
            ],
            options={
                'verbose_name_plural': 'Buses',
            },
        ),
        migrations.CreateModel(
            name='Stop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('sequence_number', models.IntegerField()),
                ('estimated_arrival_offset_minutes', models.IntegerField(default=0)),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stops', to='buses.route')),
            ],
            options={
                'ordering': ['route', 'sequence_number'],
            },
        ),
        migrations.CreateModel(
            name='PerformanceMetrics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('total_trips', models.IntegerField(default=0)),
                ('on_time_trips', models.IntegerField(default=0)),
                ('delayed_trips', models.IntegerField(default=0)),
                ('cancelled_trips', models.IntegerField(default=0)),
                ('total_passengers', models.IntegerField(default=0)),
                ('average_delay_minutes', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='metrics', to='buses.bus')),
            ],
            options={
                'verbose_name_plural': 'Performance Metrics',
                'unique_together': {('bus', 'date')},
            },
        ),
        migrations.CreateModel(
            name='Trip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('status', models.CharField(choices=[('not_started', 'Not Started'), ('running', 'Running'), ('delayed', 'Delayed'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='not_started', max_length=20)),
                ('actual_departure_time', models.DateTimeField(blank=True, null=True)),
                ('actual_arrival_time', models.DateTimeField(blank=True, null=True)),
                ('delay_minutes', models.IntegerField(default=0)),
                ('remarks', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trips', to='buses.bus')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('bus', 'date')},
            },
        ),
    ]
