# Generated by Django 5.2.4 on 2025-12-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('buses', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='performancemetrics',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='performancemetrics',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='bus',
            name='fare',
        ),
        migrations.RemoveField(
            model_name='route',
            name='distance_km',
        ),
        migrations.RemoveField(
            model_name='route',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='trip',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='stop',
            name='distance_from_previous_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='stop',
            name='fare_from_previous',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AlterField(
            model_name='bus',
            name='amenities',
            field=models.TextField(blank=True),
        ),
        migrations.AlterUniqueTogether(
            name='stop',
            unique_together={('route', 'sequence_number')},
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seat_number', models.CharField(max_length=5)),
                ('is_window', models.BooleanField(default=False)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='buses.bus')),
            ],
        ),
    ]
