# Generated by Django 5.2.4 on 2025-12-25 07:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0001_initial'),
        ('buses', '0002_alter_performancemetrics_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='booking',
            name='boarding_point',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='dropping_point',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='updated_at',
        ),
        migrations.AddField(
            model_name='booking',
            name='distance_km',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=8),
        ),
        migrations.AddField(
            model_name='booking',
            name='from_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_from', to='buses.stop'),
        ),
        migrations.AddField(
            model_name='booking',
            name='selected_seats',
            field=models.ManyToManyField(blank=True, to='buses.seat'),
        ),
        migrations.AddField(
            model_name='booking',
            name='to_stop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bookings_to', to='buses.stop'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='trip',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='buses.trip'),
        ),
    ]
